# To use:
  # $ conda env create -f environment.yml
  # $ conda activate cv
name: ML
dependencies:
    - python=3.10
    - ipykernel
    - numpy
    - pandas
    - scikit-learn
    - matplotlib
    - pytorch
    - pytorch-lightning
    - tensorboard
